# Generated by Django 4.2.7 on 2023-11-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='service',
            new_name='service_name',
        ),
        migrations.AlterUniqueTogether(
            name='password',
            unique_together=set(),
        ),
    ]
